name: CUNet
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8.*
  - numpy=1.20.*
  - pytorch=1.8.*
  - torchvision=0.9.*
  - cudatoolkit=11.1
  - pip=20.2.*
  - pip:
    - pytorch-lightning
    - pytorch-lightning-bolts
    - torchio
    - einops
