name: CUNet
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.*
  - numpy=1.20.*
  - pytorch=1.9.*
  - torchvision=0.10.*
  - cudatoolkit=11.1.*
  - pip=20.2.*
  - pip:
    - pytorch-lightning
    - pytorch-lightning-bolts
    - torchio
    - einops
