name: CUNet
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.*
  - numpy=1.20.*
  - pytorch=1.9.*
  - torchvision=0.10.*
  - cudatoolkit=11.1.*
  - pip=20.2.*
  - pip:
    - pytorch-lightning==1.3.*
    - pytorch-lightning-bolts==0.3.*
    - torchio==0.18.*
    - einops==0.3.*
    - pymia==0.3.*
    - python-decouple==3.4
    - nibabel==3.2.*
